[server]
enableCORS = false
enableXsrfProtection = true
useForwardedHeaders = true
enableWebsocketCompression = false
headless = true
fileWatcherType = "none"

[theme]
base = "dark"
primaryColor = "#ff3366"
backgroundColor = "#0e0e10"
secondaryBackgroundColor = "#18181b"
textColor = "#e5e7eb"
